{ 
  "libs":[
    "javascripts/entourage.js"
  ],  
	"suites":[
  	"core/browser.js",
  	"core/compiler.js",
  	"mq/mq.js",
  	"wel/actions.js",
  	"wel/dom_conditions.js",
  	"wel/effects_jquery.js",
  	"wel/forms.js",
  	"wel/key_conditions.js",
  	"wel/interaction_conditions.js",
  	"wel/messaging.js",
  	"wel/parser.js",
  	"wel/api.js"
	]
} 
